### ISSUE TITLE
SchemaRegistry - 404 not found

### ISSUE THREAD

**Issue by karthit** [hortonworks-spark/spark-schema-registry#8]
Hi, 

Im using confluent schema registry latest version. Im passing schema.registry.url -> http://SERVER:PORT/ and my topic name which is already created in schema registry endpoint.
curl returns a valid schema json from this endpoint,http://SERVER:PORT/subjects/TOPIC/versions/latest

but while using from_sr, im getting http error 404 not found

**Comment by arunmahadevan** [comment]
You need to use https://github.com/hortonworks/registry

Set `schema.registry.url -> http://SERVER:PORT/api/v1/`
Also check the logs to see whats going on.

**Comment by karthit** [comment]
Thanks, that helps!
